# Generated by Django 4.1 on 2022-08-08 14:55

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('cnic', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', djrichtextfield.models.RichTextField()),
                ('price', models.IntegerField()),
                ('category', djrichtextfield.models.RichTextField()),
                ('photo_one', models.ImageField(upload_to='users/')),
                ('photo_two', models.ImageField(upload_to='users/')),
            ],
        ),
    ]
