# Generated by Django 4.1 on 2022-08-08 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lender_cnic_alter_lender_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
